name: Fresh to vercel PR

on:
  pull_request:

jobs:
  createExampleAndDeployToArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      - name: Build with Hugo on PR
        working-directory: exampleSite
        run: |
          hugo \
            --minify \
            --baseURL https://hugo-fresh-${{ github.event.pull_request.head.user.login }}-${{ github.event.pull_request.head.ref }}.vercel.app

      - name: Save hugo as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hugo-output
          path: exampleSite/public/

      - name: Save alias domain
        run: |
          mkdir -p ./alias-domain
          echo hugo-fresh-${{ github.event.pull_request.head.user.login }}-${{ github.event.pull_request.head.ref }}.vercel.app > ./alias-domain/alias-domain

      - name: Save alias domain as artifact
        uses: actions/upload-artifact@v3
        with:
          name: alias-domain
          path: alias-domain/